### ISSUE TITLE
aws_ena_driver_version warning

### ISSUE THREAD

**Issue by Bukashk0zzz** [azavea/ansible-aws-ena#6]
ansible 2.4.2.0

```yaml
---
- hosts: all
  vars:
    aws_ena_driver_version: '1.2.0'
  pre_tasks:
    - name: Update APT cache
      apt: update_cache=true

  roles:
    - role: azavea.aws-ena
```

All install correct but with warning:
[WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: ena_driver_version.stdout != "{{ aws_ena_driver_version }}"
